<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        $locations = [
            ['name' => 'Nairobi', 'type' => 'county'],
            ['name' => 'Mombasa', 'type' => 'county'],
            ['name' => 'Nakuru', 'type' => 'county'],
            ['name' => 'Kiambu', 'type' => 'county'],
            ['name' => 'Kisumu', 'type' => 'county'],
            ['name' => 'Machakos', 'type' => 'county'],
            ['name' => 'Kajiado', 'type' => 'county'],
            ['name' => 'Uasin Gishu', 'type' => 'county'],
            ['name' => 'Kilifi', 'type' => 'county'],
            ['name' => 'Meru', 'type' => 'county'],
            ['name' => 'Nyeri', 'type' => 'county'],
            ['name' => 'Embu', 'type' => 'county'],
            ['name' => 'Kakamega', 'type' => 'county'],
            ['name' => 'Bungoma', 'type' => 'county'],
            ['name' => 'Bomet', 'type' => 'county'],
            ['name' => 'Kisii', 'type' => 'county'],
            ['name' => 'Migori', 'type' => 'county'],
            ['name' => 'Homa Bay', 'type' => 'county'],
            ['name' => 'Siaya', 'type' => 'county'],
            ['name' => 'Vihiga', 'type' => 'county'],
            ['name' => 'Trans Nzoia', 'type' => 'county'],
            ['name' => 'Nandi', 'type' => 'county'],
            ['name' => 'Elgeyo Marakwet', 'type' => 'county'],
            ['name' => 'Baringo', 'type' => 'county'],
            ['name' => 'Laikipia', 'type' => 'county'],
            ['name' => 'Nyandarua', 'type' => 'county'],
            ['name' => "Murang'a", 'type' => 'county'],
            ['name' => 'Kirinyaga', 'type' => 'county'],
            ['name' => 'Tharaka Nithi', 'type' => 'county'],
            ['name' => 'Isiolo', 'type' => 'county'],
            ['name' => 'Garissa', 'type' => 'county'],
            ['name' => 'Wajir', 'type' => 'county'],
            ['name' => 'Mandera', 'type' => 'county'],
            ['name' => 'Marsabit', 'type' => 'county'],
            ['name' => 'Samburu', 'type' => 'county'],
            ['name' => 'Turkana', 'type' => 'county'],
            ['name' => 'West Pokot', 'type' => 'county'],
            ['name' => 'Lamu', 'type' => 'county'],
            ['name' => 'Taita Taveta', 'type' => 'county'],
            ['name' => 'Kwale', 'type' => 'county'],
            ['name' => 'Tana River', 'type' => 'county'],
            ['name' => 'Narok', 'type' => 'county'],
            ['name' => 'Kericho', 'type' => 'county'],
            ['name' => 'Nyamira', 'type' => 'county'],
            ['name' => 'Rachuonyo', 'type' => 'county'],

            ['name' => 'James Gichuru Road', 'type' => 'road'],
            ['name' => 'Southern Bypass', 'type' => 'road'],
            ['name' => 'Gitanga Road', 'type' => 'road'],
            ['name' => 'Naivasha Road', 'type' => 'road'],
            ['name' => 'Northern Bypass', 'type' => 'road'],
            ['name' => 'Eastern Bypass', 'type' => 'road'],
            ['name' => 'Manyanja Rd', 'type' => 'road'],
            ['name' => 'Waiyaki Way', 'type' => 'road'],
            ['name' => 'Kiambu Road', 'type' => 'road'],
            ['name' => 'Langata Road', 'type' => 'road'],
            ['name' => 'Outering Road', 'type' => 'road'],
            ['name' => 'Kangundo Road', 'type' => 'road'],
            ['name' => 'Ngong Road', 'type' => 'road'],
            ['name' => 'Kamiti Road', 'type' => 'road'],
            ['name' => 'Jogoo Road', 'type' => 'road'],
            ['name' => 'Mombasa Road', 'type' => 'road'],
            ['name' => 'Thika Road', 'type' => 'road'],

            ['name' => 'Allsops', 'type' => 'area'],
            ['name' => 'Banana', 'type' => 'area'],
            ['name' => 'Buruburu', 'type' => 'area'],
            ['name' => 'Chokaa', 'type' => 'area'],
            ['name' => 'Dagoretti', 'type' => 'area'],
            ['name' => 'Dandora', 'type' => 'area'],
            ['name' => 'Donholm', 'type' => 'area'],
            ['name' => 'Eastlands', 'type' => 'area'],
            ['name' => 'Eastleigh', 'type' => 'area'],
            ['name' => 'Embakasi', 'type' => 'area'],
            ['name' => 'Garden City', 'type' => 'area'],
            ['name' => 'Githurai 44', 'type' => 'area'],
            ['name' => 'Githurai 45', 'type' => 'area'],
            ['name' => 'Hurlingham', 'type' => 'area'],
            ['name' => 'Huruma', 'type' => 'area'],
            ['name' => 'Imara Daima', 'type' => 'area'],
            ['name' => 'Jamhuri', 'type' => 'area'],
            ['name' => 'Joska', 'type' => 'area'],
            ['name' => 'Juja', 'type' => 'area'],
            ['name' => 'Kabete', 'type' => 'area'],
            ['name' => 'Kahawa Sukari', 'type' => 'area'],
            ['name' => 'Kahawa Wendani', 'type' => 'area'],
            ['name' => 'Kahawa West', 'type' => 'area'],
            ['name' => 'Kamulu', 'type' => 'area'],
            ['name' => 'Kangemi', 'type' => 'area'],
            ['name' => 'Karen', 'type' => 'area'],
            ['name' => 'Kariobangi', 'type' => 'area'],
            ['name' => 'Kasarani', 'type' => 'area'],
            ['name' => 'Kawangware', 'type' => 'area'],
            ['name' => 'Kayole', 'type' => 'area'],
            ['name' => 'Kenyatta Road', 'type' => 'area'],
            ['name' => 'Kibera', 'type' => 'area'],
            ['name' => 'Kikuyu', 'type' => 'area'],
            ['name' => 'Kileleshwa', 'type' => 'area'],
            ['name' => 'Kilimani', 'type' => 'area'],
            ['name' => 'Kitengela', 'type' => 'area'],
            ['name' => 'Kitisuru', 'type' => 'area'],
            ['name' => 'Komarock', 'type' => 'area'],
            ['name' => 'Langata', 'type' => 'area'],
            ['name' => 'Lavington', 'type' => 'area'],
            ['name' => 'Loresho', 'type' => 'area'],
            ['name' => 'Madaraka', 'type' => 'area'],
            ['name' => 'Makadara', 'type' => 'area'],
            ['name' => 'Malaa', 'type' => 'area'],
            ['name' => 'Mathare', 'type' => 'area'],
            ['name' => 'Milimani', 'type' => 'area'],
            ['name' => 'Mlolongo', 'type' => 'area'],
            ['name' => 'Muthaiga', 'type' => 'area'],
            ['name' => 'Muthangari', 'type' => 'area'],
            ['name' => 'Muthurwa', 'type' => 'area'],
            ['name' => 'Mwiki', 'type' => 'area'],
            ['name' => 'Nairobi Town', 'type' => 'area'],
            ['name' => 'Nairobi West', 'type' => 'area'],
            ['name' => 'Ndenderu', 'type' => 'area'],
            ['name' => 'Ngara', 'type' => 'area'],
            ['name' => 'Ngong', 'type' => 'area'],
            ['name' => 'Ngumba', 'type' => 'area'],
            ['name' => 'Njiru', 'type' => 'area'],
            ['name' => 'Pangani', 'type' => 'area'],
            ['name' => 'Parklands', 'type' => 'area'],
            ['name' => 'Roasters', 'type' => 'area'],
            ['name' => 'Ongata Rongai', 'type' => 'area'],
            ['name' => 'Roysambu', 'type' => 'area'],
            ['name' => 'Ruai', 'type' => 'area'],
            ['name' => 'Ruaka', 'type' => 'area'],
            ['name' => 'Ruaraka', 'type' => 'area'],
            ['name' => 'Ruiru', 'type' => 'area'],
            ['name' => 'Runda', 'type' => 'area'],
            ['name' => 'Saika', 'type' => 'area'],
            ['name' => 'South B', 'type' => 'area'],
            ['name' => 'South C', 'type' => 'area'],
            ['name' => 'Syokimau', 'type' => 'area'],
            ['name' => 'Thogoto', 'type' => 'area'],
            ['name' => 'Thome', 'type' => 'area'],
            ['name' => 'Umoja', 'type' => 'area'],
            ['name' => 'Upper Hill', 'type' => 'area'],
            ['name' => 'Utawala', 'type' => 'area'],
            ['name' => 'Uthiru', 'type' => 'area'],
            ['name' => 'Westlands', 'type' => 'area'],
        ];

        foreach ($locations as $location) {
            Location::updateOrCreate(
                ['name' => $location['name']],
                [
                    'type' => $location['type'],
                    'is_active' => true,
                ]
            );
        }
    }
}
